Update to CSharp DotNet version 4 by default
Addresses errors such as the following:
Command.cs(91,7): error CS0246: The type or namespace name 'var' could
not be found (are you missing a using directive or an assembly
reference?), which occour after the update to SWIG 4.1.1.