Remove usage of std::filesystem::path
Addresses OSX compilation error:
 error: 'path' is unavailable: introduced in macOS 10.15

This is encountered when the OSX deployment target is set to an older
version for compatibility in the Python packaging.