COMP: Clang requires explicit Disambiguation
This is explained at:
http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=388

SimpleITK/Code/Common/include/Ancillary/TypeList.h:457:13: error: use 'template' keyword to treat 'visitRHS' as a dependent template name
          goRight.visitRHS<Visitor>( visitor );
                  ^
                  template